apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-web-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-web

  template:
    metadata:
      labels:
        app: devops-web

    spec:
      containers:
        - name: devops-container
          image: dev1:1
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 80